import test from 'node:test';
import assert from 'node:assert/strict';
import {input,tabelogURL,validatePage} from '../lib/core.js';
import {runSearch} from '../lib/pipeline.js';
import {readEvents} from '../public/stream.js';
import handler from '../api/search.js';
const url='https://tabelog.com/tokyo/A1/A2/12345678/';
const p={id:'p',name:'店 本店',address:'東京都新宿区1-2-3'};
const row={name:'店 本店',address:p.address,score:3.65,url,branchMatch:true};
const meta={urlMetadata:[{retrievedUrl:url,urlRetrievalStatus:'URL_RETRIEVAL_STATUS_SUCCESS'}]};
test('input and domain safety',()=>{assert.throws(()=>input({city:'',food:'ラーメン'}));assert.equal(tabelogURL('https://tabelog.com.evil.test/12345678/'),null);});
test('page evidence requires retrieval success, branch/address/score checks',()=>{assert.equal(validatePage(p,row,url,meta).score,3.65);assert.equal(validatePage(p,row,url,{}),null);assert.equal(validatePage(p,{...row,address:'大阪府大阪市1-2-3'},url,meta),null);assert.equal(validatePage(p,{...row,branchMatch:false},url,meta),null);assert.equal(validatePage(p,{...row,score:6},url,meta),null);});
test('stream decoder preserves Korean and split JSON chunks',async()=>{const raw=new TextEncoder().encode('{"type":"places","name":"신주쿠"}\n{"type":"done"}\n');const stream=new ReadableStream({start(c){for(let i=0;i<raw.length;i+=2)c.enqueue(raw.slice(i,i+2));c.close();}});const events=[];await readEvents(stream,e=>events.push(e));assert.equal(events[0].name,'신주쿠');assert.equal(events[1].type,'done');});
test('places emitted first, only three inspections run concurrently, failure retains all candidates',async()=>{let active=0,max=0,calls=0;const events=[];await runSearch({},e=>events.push(structuredClone(e)),new AbortController().signal,{placesSearch:async()=>Array.from({length:6},(_,i)=>({...p,id:String(i)})),inspectPlace:async p=>{calls++;active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,10));active--;if(p.id==='1')throw Error('timeout');return {tabelog:null,message:'unknown'};},rankPlaces:async()=>{throw Error('unavailable');}});assert.equal(events[0].type,'places');assert.equal(calls,3);assert.equal(max,3);const done=events.at(-1);assert.equal(done.type,'done');assert.equal(done.restaurants.length,6);assert.equal(done.restaurants[1].checkStatus,'unknown');assert.equal(done.restaurants[3].checkStatus,'skipped');assert.equal(done.aiRanked,false);});
test('empty results do not call Gemini',async()=>{const events=[];await runSearch({},e=>events.push(e),new AbortController().signal,{placesSearch:async()=>[],inspectPlace:async()=>{throw Error('not expected');}});assert.equal(events.at(-1).type,'done');});
test('cancelled search does not start ranking',async()=>{const ac=new AbortController();let ranked=false;await runSearch({},()=>{},ac.signal,{placesSearch:async()=>[p],inspectPlace:async()=>{ac.abort();return {tabelog:null};},rankPlaces:async()=>{ranked=true;}});assert.equal(ranked,false);});
test('password rejection occurs before streaming',async()=>{process.env.APP_PASSWORD='secret';const res={setHeader(){},status(n){this.code=n;return this;},json(x){this.body=x;}};await handler({method:'POST',headers:{},body:{}},res);assert.equal(res.code,401);delete process.env.APP_PASSWORD;});
