import test from 'node:test';
import assert from 'node:assert/strict';
import {input,evidenceFor,tabelogURL,safeURL} from '../lib/core.js';
import handler from '../api/search.js';
test('input validation and URL safety',()=>{assert.throws(()=>input({city:'',food:'라멘'}));assert.throws(()=>input({city:'도쿄',food:'x'.repeat(61)}));assert.equal(safeURL('javascript:alert(1)'),null);assert.equal(tabelogURL('https://tabelog.com.evil.test/tokyo/12345678/'),null);});
test('score requires candidate-specific cited Tabelog support',()=>{const p={id:'p1',name:'店 本店',address:'東京都1'};const row={score:3.67,supportIndex:0};const sources=[{tabelogUrl:'https://tabelog.com/tokyo/A1/A2/12345678/'}];const support=[{text:'p1 店 本店 東京都1 Tabelog 3.67',sourceIndices:[0]}];assert.equal(evidenceFor(p,row,support,sources).score,3.67);assert.equal(evidenceFor(p,{...row,score:4.2},support,sources),null);assert.equal(evidenceFor({...p,address:'大阪'},row,support,sources),null);assert.equal(evidenceFor(p,row,support,[{}]),null);assert.equal(evidenceFor(p,{score:null},support,sources),null);});
function response(){return {statusCode:200,setHeader(){},status(n){this.statusCode=n;return this;},json(x){this.body=x;return this;}};}
test('endpoint mock integration, unknown IDs discarded and evidence accepted',async()=>{const original=global.fetch;process.env.GOOGLE_MAPS_API_KEY='test';process.env.GEMINI_API_KEY='test';delete process.env.APP_PASSWORD;
let call=0;global.fetch=async()=>{call++;const values=[{places:[{id:'p1',displayName:{text:'店'},formattedAddress:'東京',rating:4.1,userRatingCount:90}]},{candidates:[{finishReason:'STOP',content:{parts:[{text:'p1 店 東京 Tabelog 3.67'}]},groundingMetadata:{groundingChunks:[{web:{uri:'https://tabelog.com/tokyo/A1/A2/12345678/',title:'食べログ'}}],groundingSupports:[{segment:{text:'p1 店 東京 Tabelog 3.67'},groundingChunkIndices:[0]}]}}]},{candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify({restaurants:[{id:'fake',reason:'fake'},{id:'p1',score:3.67,supportIndex:0,reason:'후보 비교'}]})}]}}]}];return new Response(JSON.stringify(values[call-1]),{status:200});};
try{const res=response();await handler({method:'POST',headers:{},body:{city:'도쿄',food:'라멘'}},res);assert.equal(res.statusCode,200);assert.equal(res.body.restaurants.length,1);assert.equal(res.body.restaurants[0].tabelog.score,3.67);}finally{global.fetch=original;}});
test('auth rejects before upstream requests',async()=>{process.env.APP_PASSWORD='secret';const r=response();await handler({method:'POST',headers:{},body:{}},r);assert.equal(r.statusCode,401);delete process.env.APP_PASSWORD;});
test('AI failure preserves Google results without invented Tabelog score',async()=>{const original=global.fetch;let count=0;global.fetch=async()=>{count++;return count===1?new Response(JSON.stringify({places:[{id:'x',displayName:{text:'店'},formattedAddress:'東京'}]})):new Response('{}',{status:429});};try{const r=response();await handler({method:'POST',headers:{},body:{city:'도쿄',food:'라멘'}},r);assert.equal(r.statusCode,200);assert.equal(r.body.restaurants[0].tabelog,null);assert.equal(r.body.aiRanked,false);assert.ok(r.body.warnings.length);}finally{global.fetch=original;}});
